name: Zappa Docker Lambda Deploy
run-name: Deployment of ${{ github.repository }} through Zappa-Docker-Lambda
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_IMAGE_URI: ${{ secrets.ECR_IMAGE_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Activate a virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install Python libraries with pip
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Build Docker image
        run: docker build -t dwf2 .
      - name: Tag Docker image
        run: docker tag dwf2 $ECR_IMAGE_URI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Transfers authority from AWS ECR to Docker
        run: >
          aws ecr get-login-password |
           docker login --username AWS --password-stdin $ECR_IMAGE_URI
      - name: Push Docker image to AWS ECR
        run: docker push $ECR_IMAGE_URI
      - name: Save python settings for production with Zappa
        run: zappa save-python-settings-file prod
      - name: Deploy application from AWS ECR to Lambda with Zappa
        run: zappa update prod -d $ECR_IMAGE_URI
